### PR TITLE
Fixing exposed Database and Gmail credentials 

### PR DESCRIPTION
**Pull request by jiveshkalra**
# Fixed Issue #13 
 
- [x]  Moved all the credentials to the .env file 
- [x]  gave a sample .env file for anyone to refer to for cloning this repository

### CODE REVIEW

**Comment by Nandini80** [comment]
Send me the .env file filled data after you remove it from index.js

**Comment by jiveshkalra** [comment]
Sure, but where can I send it to you?

**Comment by Nandini80** [comment]
Send me here only

**Comment by jiveshkalra** [comment]
Sure here it is ->
```.env
DB_HOST=bk0ionmurhfxi1puzbyj-mysql.services.clever-cloud.com
DB_USER=ucdsavpfy5razlfq
DB_PASSWORD=UsyWuk7YAcE8rFXUTJGT
DB_DATABASE=bk0ionmurhfxi1puzbyj 

EMAIL_USER = nandinijindal010@gmail.com
EMAIL_PASSWORD = sbthzqsvmghfpbkl

```

**Pull request merged**
